import "./globals.css";
import Theme from "./Components/Theme";
import DarkLight from "./Components/DarkLight";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <DarkLight />
          {children}</Theme>
      </body>
    </html>
  );
}
